package:
  name: slycot
  version: 0.0.1

source:
  url: https://github.com/roryyorke/Slycot/releases/download/objcopy-1/slycot-2.dev10+ga8cc86fa0.tar.gz

build:
  number: 2
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scikit-build-core >=0.12.1             # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake >=3.17
    - make  # [unix]
    - ninja  # [win]
  host:
    - libblas
    - libcblas
    - liblapack
    - python
    - numpy
    - scikit-build-core >=0.12.1
    - pip
    - setuptools_scm >=9
  run:
    - python

test:
  requires:
    - pytest
    - scipy
  imports:
    - slycot
  commands:
    - pytest --pyargs slycot

about:
  home: https://github.com/python-control/Slycot
  dev_url: https://github.com/python-control/Slycot
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Slycot: a wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

extra:
  recipe-maintainers:
    - roryyorke
    - bnavigator
    - moorepants
    - murrayrm
    - repagh
